spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  freemarker:
    cache: true
    check-template-location: true
    charset: utf-8
    suffix: .ftl
    template-loader-path: classpath:templates/freeMarker
